#' populatingDB
#'
#' @description This function is designed to populate the studentDB with the normalised score from a specific module. IMPORTANT: the studentDB file must the the one referring to the previous verbalising exam
#' @param norm_score, the name of the variable contaning the normalised score generated by loadExam.
#' @param studentDB, a data.frame of the LATEST update of studentDB: i.e. including last verbalising exam and, every year, the new students entering in the second semester of the first year
#' @param type, a character string indicating the exam type. Four options: bioc 9 credits, bm 5 credits, gen 3 credits and biol 1 credit
#'
#' @return It returns a student database populated with the results of the students modules
#' @author Raffaele Calogero
#'
#' @examples
#' \dontrun{
#' db = utils::read.csv("somewhere/BandB/studentDB_2026-07-18.csv") #reading the latest studentDB
#' db = populatingDB(norm_score = bioc, studentDB = db, type="bioc")
#' db = populatingDB(norm_score = bioc, studentDB = db, type="bm")
#' db = populatingDB(norm_score = bioc, studentDB = db, type="gen")
#' db = populatingDB(norm_score = bioc, studentDB = db, type="biol")
#' utils::write.csv(db, paste0("/somewhere/BandB//studentDB_", format(Sys.time(), "%Y-%m-%d_%H-%M-%S"),".csv"), row.names = F) #writing the updated studentDB
#' }
#' @export
populatingDB = function(norm_score, studentDB, type=c("bioc","bm","gen","biol")){
  shrinked_df = norm_score
  updated_set = studentDB
  if(type == "bioc"){
    shrinked_df = shrinked_df[order(as.character(shrinked_df$Matricola)),]
    tmp_set = updated_set[which(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    tmp_set = tmp_set[order(as.character(tmp_set$MATRICOLA)),]
    other_set = updated_set[!(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    if(identical(as.character(tmp_set$MATRICOLA), as.character(shrinked_df$Matricola))){
      tmp_set$bioc.norm = shrinked_df$norm
      tmp_set$bioc = shrinked_df$Esito
      tmp_set$cfu = shrinked_df$CFU
    } else{
      return("We have a problem: the exam matricola is not aligned with the studentDB matricola")
    }
  } else if(type == "bm"){
    shrinked_df = shrinked_df[order(as.character(shrinked_df$Matricola)),]
    tmp_set = updated_set[which(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    tmp_set = tmp_set[order(as.character(tmp_set$MATRICOLA)),]
    other_set = updated_set[!(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    if(identical(as.character(tmp_set$MATRICOLA), as.character(shrinked_df$Matricola))){
      tmp_set$bm.norm = shrinked_df$norm
      tmp_set$bm = shrinked_df$Esito
      tmp_set$cfu = shrinked_df$CFU
    } else{
      return("We have a problem: the exam matricola is not aligned wiht the studentDB matricola")
    }
  } else if(type == "gen"){
    shrinked_df = shrinked_df[order(as.character(shrinked_df$Matricola)),]
    tmp_set = updated_set[which(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    tmp_set = tmp_set[order(as.character(tmp_set$MATRICOLA)),]
    other_set = updated_set[!(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    if(identical(as.character(tmp_set$MATRICOLA), as.character(shrinked_df$Matricola))){
      tmp_set$gen.norm = shrinked_df$norm
      tmp_set$gen = shrinked_df$Esito
      tmp_set$cfu = shrinked_df$CFU
    } else{
      return("We have a problem: the exam matricola is not aligned with the studentDB matricola")
    }
  } else if(type == "biol"){
    shrinked_df = shrinked_df[order(as.character(shrinked_df$Matricola)),]
    tmp_set = updated_set[which(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    tmp_set = tmp_set[order(as.character(tmp_set$MATRICOLA)),]
    other_set = updated_set[!(as.character(updated_set$MATRICOLA) %in% as.character(shrinked_df$Matricola)),]
    if(identical(as.character(tmp_set$MATRICOLA), as.character(shrinked_df$Matricola))){
      tmp_set$biol.norm = shrinked_df$norm
      tmp_set$biol = shrinked_df$Esito
      tmp_set$cfu = shrinked_df$CFU
    } else{
      return("We have a problem: the exam matricola is not aligned with the studentDB matricola")
    }
  }
  updated_df = rbind(tmp_set, other_set)
  updated_df = as.data.frame(updated_df)
  updated_df = updated_df[order(as.character(updated_df$MATRICOLA)),]
  return(updated_df)
  #
}